Repository Neovici/cosmoz-data-nav, pull requests merged in 2018-04, with the labels that each got.

#49 Remove _elements from computed selectedElement
  analysis.json
  cosmoz-data-nav.js
Labels: bug

#47 Fixes _isDescendantOf in Shadow DOM
  cosmoz-data-nav.js
Labels: bug

#36 Add support for hash-param
  bower.json
  cosmoz-data-nav.html
  cosmoz-data-nav.js
  demo/index.html
  yarn.lock
Labels: enhancement, minor-change

#28 Tests
  cosmoz-data-nav.js
  test/basic.html
  test/helpers/cosmoz-data-nav-resizable-view.html
  test/helpers/cosmoz-data-nav-test-view.html
  test/index.html
  test/resizable.html
Labels: enhancement
