Repository Neovici/cosmoz-data-nav, pull requests merged in 2019-03, with the labels that each got.

#74 (patch) fix selectedItem notification
  cosmoz-data-nav.js
  demo/index.html
Labels: bug

#72 2.x upgrade remove IS_V2 checks
  cosmoz-data-nav.js
  package-lock.json
  test/basic.html
  test/helpers/utils.js
  test/index.html
  test/resizable.html
  yarn.lock
Labels: enhancement

#76 Fix maintainSelection implementation
  cosmoz-data-nav.js
  test/.eslintrc.json
  test/basic.html
  test/helpers/utils.js
  test/index.html
  test/spec.html
Labels: bug, enhancement
