Repository Neovici/cosmoz-data-nav, pull requests merged in 2020-10, with the labels that each got.

#137 Feature/136 resize
  cosmoz-data-nav.js
  package-lock.json
  package.json
  shell.nix
  test/helpers/cosmoz-data-nav-resizable-view.js
  test/resizable.test.js
Labels: enhancement

#138 fix: upgrade cosmoz-bottom-bar
  package-lock.json
  package.json
Labels: dependencies, enhancement

#139 Bugfix/tweaks updates
  cosmoz-data-nav.js
  karma.conf.js
  package-lock.json
  package.json
  shell.nix
Labels: bug, enhancement
