Repository Neovici/cosmoz-data-nav, pull requests merged in 2020-06, with the labels that each got.

#118 fix(selected-instance): is always the incomplete template
  cosmoz-data-nav.js
Labels: bug

#122 fix: make sure selected instance isn't updated for preloads
  cosmoz-data-nav.js
Labels: bug

#120 feat(👻): extract cache behavior with haunted-polymer hook
  cosmoz-data-nav.js
  lib/use-cache.js
  package-lock.json
  package.json
  test/basic.test.js
Labels: enhancement

#123 fix(build): publish lib/ to npm package
  package.json
Labels: bug

#124 fix: drop iron-flex-layout
  cosmoz-data-nav.js
  demo/demo.js
  demo/helpers/cosmoz-demo-view.js
  demo/index.html
  package-lock.json
  package.json
  test/helpers/cosmoz-data-nav-test-view.js
  test/helpers/utils.js
Labels: dependencies, enhancement

#125 fix: incomplete instance styling
  cosmoz-data-nav.js
Labels: bug

#129 fix: make sure to only _forwardHostProp on instance templates
  cosmoz-data-nav.js
Labels: bug
